export const WORDS = [
  'vukka', //屋卡:vuk5 ka1
  'congi', //初二:co1 ngi4
  'tiluk', //第六:ti4 luk5
  'hiziu', //喜酒:hi3 ziu3
  'kinge', //傾計:kin1 ge4
  'tonam', //斷暗:ton1 am4
  'buvok', //補鑊:bu3 vok4
  'fopin', //和平:fo2 pin2
  'hanki', //限期:han4 ki2
  'vinca', //暈車:vin2 ca1
  'sisit', //死食:si3 sit6
  'siong', //箱:siong1,像:siong3,象:siong4,相:siong4
  'yikui', //衣櫃:yi1 kui4
  'sinse', //身世:sin1 se4
  'sukti', //速遞:suk5 ti4
  'masak', //麻石:ma2 sak6
  'lamci', //男廁:lam2 ci4
  'tauli', //道理:tau4 li1
  'ngiau', //尿:ngiau4
  'hiong', //香:hiong1,鄉:hiong1,響:hiong3,向:hiong4
  'euyen', //歐元:eu1 yen2
  'kosit', //課室:ko4 sit5
  'lusun', //蘆筍:lu1 sun3
  'liyiu', //理由:li1 yiu2
  'funga', //分家:fun1 ga1
  'sesam', //洗衫:se3 sam1
  'tamvu', //貪污:tam1 vu1
  'likui', //理虧:li1 kui1
  'samok', //沙漠:sa1 mok5
  'ciame', //且姆:cia1 me1
  'paupu', //跑步:pau3 pu4
  'siheu', //時候:si2 heu4
  'sinzi', //信紙:sin4 zi3
  'apyit', //鴨翼:ap5 yit6
  'teuza', //豆渣:teu4 za1
  'teufa', //豆花:teu4 fa1
  'kolok', //可樂:ko3 lok6
  'ziong', //漿:ziong1,獎:ziong3,醬:ziong4
  'sukpo', //叔婆:suk5 po2
  'zitng', //鯽魚:zit5 ng2
  'giung', //弓:giung1,供:giung4
  'vutli', //物理:vut6 li1
  'geuci', //狗牸:geu3 ci4
  'lemse', //腍柿:lem2 se2
  'bungi', //畚箕:bun4 gi1
  'sinca', //新車 :sin1 ca1
  'gisiu', //舉手:gi3 siu3
  'setzu', //虱子:set5 zu1
  'hagau', //蝦餃:ha1 gau3
  'yenfo', //煙火:yen2 fo3
  'hicin', //起程:hi3 cin2
  'kausi', //考試:kau3 si4
  'ngiun', //忍:ngiun1,韌:ngiun4
  'gaset', //假設:ga3 set5
  'sufap', //書法:su1 fap5
  'goloi', //過來:go4 loi2
  'lokmu', //落霧:lok6 mu4
  'suiku', //水庫:sui3 ku4
  'baden', //趴等:ba1 den3
  'tifat', //體罰:ti3 fat6
  'sacuk', //畬族:sa2 cuk6
  'zauha', //灶下:zau4 ha1
  'gitsi', //幾時:git5 si2
  'yimin', //移民:yi2 min2
  'hauma', //號碼:hau4 ma1
  'zuzit', //組織:zu3 zit5
  'biteu', //陂頭:bi1 teu2
  'tuksu', //讀書:tuk6 su1
  'hamng', //鹹魚:ham2 ng2
  'ngioi', //艾:ngioi4
  'cuheu', //粗口:cu1 heu3
  'caleu', //茶樓:ca2 leu2
  'punpi', //笨皮:pun1 pi2
  'fokiu', //火球:fo3 kiu2
  'hansi', //限時:han4 si2
  'fosui', //火水:fo3 sui3
  'eucai', //漚祡:eu4 cai2
  'luteu', //爐頭:lu2 teu2
  'mamoi', //孖妹:ma1 moi4
  'kingi', //歧義:ki2 ngi4
  'gaufa', //膠花:gau1 fa1
  'suiap', //水鴨:sui3 ap5
  'zihap', //紙盒:zi3 hap6
  'fansu', //番薯:fan1 su2
  'gaban', //加班:ga1 ban1
  'misui', //米碎:mi3 sui4,沕水:mi4 sui3
  'sevon', //洗碗:se3 von2
  'fokui', //貨櫃:fo4 kui4
  'zuteu', //豬頭:zu1 teu2
  'sesiu', //洗手:se3 siu3
  'donfu', //短褲:don3 fu4
  'gagon', //家官:ga1 gon1
  'poteu', //婆頭:po2 teu2
  'laugo', //老哥:lau3 go1
  'lipin', //禮品:li1 pin3
  'cusin', //自信:cu4 sin4
  'aideu', //哎兜:ai2 deu1,哎兜:ai4 deu1
  'yizok', //衣著:yi1 zok5
  'caipo', //差婆:cai1 po2
  'vugui', //烏龜:vu1 gui1
  'zinfu', //政府:zin4 fu3
  'puteu', //鋪頭:pu4 teu2
  'taiha', //大廈:tai4 ha4
  'ngihi', //義氣:ngi4 hi4
  'luidu', //內肚:lui4 du3
  'haziu', //下晝:ha1 ziu4
  'sakgu', //石牯:sak6 gu3
  'pikiu', //皮球:pi2 kiu2
  'ngang', //硬:ngang4
  'busam', //補衫:bu3 sam1
  'kaizu', //筷子:kai4 zu3
  'sumat', //絲襪:su1 mat5
  'cacau', //扯草:ca3 cau3
  'gukhi', //谷氣:guk5 hi4
  'busip', //補習:bu3 sip6
  'misit', //迷失:mi2 sit5
  'gofut', //果核:go3 fut6
  'vuteu', //烏頭:vu1 teu2,烏豆:vu1 teu4,芋頭:vu4 teu2
  'hosui', //河水:ho2 sui3
  'vulon', //芋卵:vu4 lon3
  'pitoi', //被袋:pi1 toi4
  'liong', //両:liong1,涼:liong2,兩:liong3,量:liong4
  'caico', //在座:cai4 co4
  'baung', //鮑魚:bau1 ng2
  'ngiok', //弱:ngiok6
  'cuyiu', //自由:cu4 yiu2
  'buntu', //本土:bun3 tu3
  'yaugo', //腰果:yau1 go3
  'yiuyi', //有意:yiu1 yi4
  'amhoi', //暗嗨:am4 hoi1
  'hihon', //稀罕:hi1 hon4
  'gigin', //機警:gi1 gin3
  'onlen', //安寧:on1 len2
  'pitpo', //蝠婆:pit6 po2
  'getdu', //蟈肚:get6 du3
  'agung', //阿公:a1 gung1
  'mazai', //孖仔:ma1 zai3,麻仔:ma2 zai3
  'masok', //麻索:ma2 sok5
  'lakia', //蝲䗁:la2 kia2
  'zinhe', //真係:zin1 he4
  'pisui', //鼻水:pi4 sui3
  'bunti', //本地:bun3 ti4
  'luzai', //路仔:lu4 zai3
  'hensi', //顯示:hen3 si4
  'daton', //打團:da3 ton2
  'foson', //貨船:fo4 son2
  'pinsi', //平時:pin2 si2
  'pizun', //樸准:pi1 zun3
  'favun', //花紋:fa1 vun2
  'ginzi', //經濟:gin1 zi4
  'leuya', //漏夜:leu4 ya4
  'holak', //河壢:ho2 lak5
  'camdo', //差唔多:ca1 m1 do1
  'laucu', //老鼠:lau4 cu3
  'miteu', //眉豆:mi2 teu4
  'fuheu', //戶口:fu4 heu3
  'laisi', //瀨屎:lai2 si3
  'dalok', //打落:da3 lok6
  'bavui', //霸位:ba4 vui4
  'zutai', //豬蹄:zu1 tai2
  'cutse', //出世:cut5 se4
  'ngiuk', //肉:ngiuk5
  'apcun', //鴨春:ap5 cun1
  'mdisi', //唔知死:m1 di1 si3
  'suiyi', //水衣:sui3 yi1
  'yacoi', //椰菜:ya2 coi4
  'liusu', //柳樹:liu1 su4
  'yazai', //葉仔:ya2 zai3
  'ngisi', //耳屎:ngi3 si3
  'taigu', //大姑:tai4 gu1
  'gumun', //顧問:gu4 mun4
  'moifa', //梅花:moi2 fa1
  'liuyi', //留意:liu2 yi4
  'tilai', //地泥:ti4 lai2
  'muili', //美麗:mui1 li4
  'landu', //爛賭:lan4 du3
  'yunsu', //運輸:yun4 su1
  'fusui', //戽水:fu4 sui3
  'zucoi', //煮菜:zu3 coi4
  'sinti', //身體:sin1 ti3
  'pauma', //跑馬:pau3 ma1
  'zuset', //紫色:zu3 set5
  'fasim', //花心:fa1 sim1
  'gonti', //官地:gon1 ti4
  'vunvu', //文武:vun2 vu1
  'fuige', //會計:fui4 ge4
  'duzai', //賭仔:du3 zai3
  'cayap', //茶葉:ca2 yap6
  'zusak', //豬石:zu1 sak6
  'sucoi', //素菜:su4 coi4
  'yisui', //雨水:yi3 sui3
  'setma', //舌嫲:set6 ma2
  'gulau', //古老:gu3 lau3
  'fazun', //花樽:fa1 zun1
  'zucap', //豬雜:zu1 cap6
  'lipma', //笠嫲:lip5 ma2
  'kaiti', //快遞:kai4 ti4
  'lenga', //嬭瓜:len4 ga
  'cuzit', //辭職:cu2 zit5
  'siufa', //繡花:siu4 fa1
  'gaisi', //雞屎:gai1 si4,街市:gai1 si4
  'zusan', //資產:zu1 san3
  'caluk', //車轆:ca1 luk5
  'yilai', //倚賴:yi3 lai4
  'kemsu', //蟾蜍:kem2 su2
  'sukse', //縮細:suk5 se4
  'siang', //腥:siang1,醒:siang3,姓:siang4
  'magau', //罵交:ma4 gau1
  'fofoi', //火灰:fo3 foi1
  'gimli', //錦鯉:gim3 li1
  'lukca', //綠茶:luk6 ca2
  'losit', //攞食:lo1 sit6
  'zucit', //主席:zu3 cit6
  'sokma', //索嫲:sok5 ma2,勺嫲:sok6 ma2
  'tohai', //拖鞋:to1 hai2
  'linsa', //鄰舍:lin2 sa4
  'pauhi', //拋棄:pau1 hi4
  'gutin', //固定:gu4 tin4
  'paklu', //白露:pak6 lu4
  'siket', //時刻:si2 ket5
  'moizu', //妹子:moi4 zu1
  'cidau', //遲到:ci2 dau4
  'gausu', //教書:gau1 su1
  'funmu', //墳墓:fun2 mu4
  'puipo', //肥婆:pui2 po2
  'zokpa', //桌帕:zok5 pa4
  'zusit', //煮食:zu3 sit6
  'gakli', //隔籬:gak5 li2
  'mamui', //馬尾:ma1 mui1
  'yazip', //椰汁:ya2 zip5
  'zulan', //豬欄:zu1 lan2
  'lanfa', //蘭花:lan2 fa1
  'loisu', //萊絲:loi4 su1
  'fayen', //花園:fa1 yen2
  'lausi', //腦屎:lau3 si3
  'gandi', //關帝:gan1 di4
  'dayin', //打印:da3 yin4
  'hasuk', //下屬:ha4 suk6
  'hoici', //開始:hoi3 ci3
  'aiden', //挨等:ai1 den3,矮凳:ai3 den4
  'ngcon', //午餐:ng3 con1
  'gavui', //價位:ga4 vui4
  'dalap', //打蠟:da3 lap6
  'zusim', //豬心:zu1 sim1
  'yuizu', //乳豬:yui1 zu1
  'citzu', //侄子:cit6 zu1
  'gimng', //金魚:gim1 ng2
  'mazui', //麻醉:ma2 zui4
  'fetza', //或者:fet6 za3
  'lokca', //落差:lok6 ca1
  'gafui', //咖啡:ga1 fui1
  'lopet', //蘿蔔:lo2 pet6
  'simgi', //心機:sim1 gi1
  'gimsa', //金沙:gim1 sa1
  'suifu', //水壺:sui3 fu2
  'zammi', //粘米:zam1 mi3
  'fafui', //花費:fa1 fui4
  'eulai', //漚泥:eu4 lai2
  'suktu', //速度:suk5 tu3
  'dosui', //躲水:do3 sui3
  'siyiu', //豉油:si4 yiu2
  'gasuk', //家屬:ga1 suk6
  'ngayi', //牙醫:nga2 yi1
  'gonyi', //乾衣:gon1 yi1
  'lanbu', //爛布:lan4 bu4
  'yaupo', //鷂婆:yau4 po2
  'fotan', //火炭:fo3 tan4
  'causu', //抄書:cau1 su1,抄書:cau1 su4,造事:cau4 su4
  'giyit', //記憶:gi4 yit5
  'gimak', //金戹:gim1 ak5
  'docia', //多謝:do1 cia4
  'ngong', //戇:ngong4
  'lilun', //理論:li1 lun4
  'zunpi', //準備:zun3 pi4
  'yiung', //魷魚:yiu2 ng2
  'zumui', //豬尾:zu1 mui1
  'gimhi', //金禧:gim1 hi1
  'badai', //孭帶:ba2 dai4
  'pideu', //被竇:pi2 deu4
  'midai', //謎底:mi2 dai3
  'zugim', //資金:zu1 gim1
  'yizai', //姨在:yi2 zai3
  'gauyi', //交椅:gau4 yi3
  'masin', //麻繩:ma2 sin2
  'hiung', //胸:hiung1,兄:hiung1,雄:hiung2
  'cuthi', //出去:cut5 hi4
  'aikip', //埃及:ai1 kip6
  'gimga', //金瓜:gim4 ga1
  'gisak', //基石:gi1 sak6
  'satan', //沙灘:sa1 tan1
  'funfu', //吩咐:fun1 fu4
  'potai', //婆太:po2 tai4
  'yiloi', //以來:yi1 loi2
  'songo', //酸果:son1 go3
  'zumau', //豬毛:zu1 mau1
  'fapli', //法例:fap6 li4
  'gusit', //姑息:gu1 sit5,股息:gu3 sit5
  'hakga', //客家:hak5 ga1
  'buteu', //斧頭:bu3 teu3
  'ligai', //理解:li1 gai3
  'guklu', //焗爐:guk6 lu2
  'suica', //水車:sui3 ca2
  'zinpu', //進步:zin4 pu4
  'fasin', //化身:fa4 sin1
  'anggo', //罌哥:ang1 go1
  'baufu', //保護:bau3 fu4,豹虎:bau4 fu3
  'emzoi', //掩啜:em1 zoi4
  'vogon', //禾稈:vo2 gon3
  'gongo', //乾果:gon1 go3
  'gazai', //架仔:ga4 zai3
  'yikiu', //依舊:yi1 kiu4
  'cuyit', //鼠疫:cu3 yit6
  'suili', //水利:sui3 li4
  'aivui', //哎位:ai2 vui4,哎位:ai4 vui4
  'tivui', //地位:ti4 vui4
  'ciabo', //斜坡:cia2 bo1
  'piang', //平:piang2,病:piang4
  'zutan', //子彈:zu3 tan2
  'giang', //驚:giang1,頸:giang3
  'ngmui', //魚尾:ng2 mui1
  'tizit', //體質:ti3 zit5
  'ngagu', //芽菇:nga2 gu1
  'ngosi', //餓死:ngo4 si3
  'zapma', //紮馬:zap5 ma1
  'sigan', //時間:si2 gan1
  'toicu', //袋鼠:toi4 cu3
  'laigo', //荔果:lai1 go3
  'taibu', //大埔:tai4 bu4
  'zuksu', //竹薯:zuk5 su3
  'ginli', //經歷:gin1 li1
  'suvun', //斯文:su1 vun2
  'moilu', //煤爐:moi2 lu2
  'dugui', //賭鬼:du3 gui3
  'fukhi', //福氣:fuk5 hi4
  'taisu', //剃鬚:tai4 su1
  'puiga', //肺瓜:pui4 ga1
  'yageu', //野狗:ya1 geu3
  'doyun', //多雲:do1 yun2
  'hakhi', //客氣:hak5 hi4
  'fagau', //花膠:fa1 gau1
  'gonbi', //乾蜱:gon1 bi1
  'apkin', //鴨肫:ap5 kin1
  'munla', //門罅:mun2 la4
  'hoica', //開車:hoi1 ca1
  'yiciu', //宇宙:yi3 ciu4
  'kimsa', //琴蛇:kim2 sa2
  'samfu', //衫褲:sam1 fu4
  'heugo', //猴哥:heu2 go1
  'yaksu', //搖手:yak6 su3
  'tiban', //地板:ti4 ban1
  'pakgo', //白果:pak6 go3
  'panvo', //拌禾:pan1 vo2
  'lokto', //駱駝:lok5 to2
  'haboi', //下背:ha1 boi4
  'guvun', //古文:gu1 vun2
  'gukyi', //穀雨:guk5 yi3
  'oicin', //愛情:oi4 cin2
  'sinpi', //信婆:sin4 pi2
  'tucoi', //圖菜:tu2 coi4
  'yihok', //醫學:yi1 hok6
  'matai', //馬蹄:ma1 tai2
  'samcu', //三次:sam1 cu4
  'onlok', //安樂:on1 lok6
  'getki', //國旗:get5 ki2
  'fonhi', //歡喜:fon1 hi3
  'lisit', //利息:li4 sit5
  'suiga', //水瓜:sui3 ga1
  'pakfa', //白話:pak6 fa1,白花:pak6 fa1
  'diboi', //裡背:di1 boi4
  'penli', //便宜:pen2 li2
  'vuzai', //芋仔:vu4 zai3
  'lihoi', //厲害:li4 hoi4
  'zuzai', //豬仔:zu1 zai1
  'dasau', //打掃:da3 sau4
  'gisim', //居心:gi1 sim1
  'lipti', //立體:lip6 ti3
  'euziu', //歐洲:eu1 ziu1
  'sunzu', //孫子:sun1 zu1
  'fuigi', //飛機:fui1 gi1
  'kiupo', //舅婆:kiu1 po2
  'yamzu', //閹豬:yam1 zu1
  'sitma', //虱嫲:sit5 ma2
  'bunsu', //本事:bun3 su4
  'taung', //討魚:tau3 ng2
  'tinsi', //定時:tin4 si2
  'buyau', //俯腰:bu1 yau1
  'zingi', //際遇:zi4 ngi4
  'yazia', //爺姐:ya2 zia3
  'aucai', //拗柴:au3 cai2
  'geugu', //狗牯:geu3 gu3
  'fufit', //狐拂:fu2 fit5
  'kingo', //企鵝:ki1 ngo2
  'sauap', //燒鴨:sau1 ap5
  'banlu', //半路:ban4 lu4
  'senli', //生意:sen1 li1
  'diget', //帝國:di4 get5
  'sunse', //孫婿:sun1 se4
  'aubau', //拗爆:au4 bau3
  'kiaza', //擎遮:kia2 za1
  'guzai', //姑仔:gu1 zai3,古仔:gu3 zai3
  'zatan', //炸彈:za4 tan2
  'gingi', //機遇:gi1 ngi4,經紀:gin1 gi3
  'sanga', //射牙:sa4 nga2
  'hisui', //汽水:hi4 sui3
  'hansu', //閒事:han2 su4
  'lideu', //蟻竇:li1 deu4
  'titeu', //地豆:ti4 teu4
  'daifu', //底褲:dai3 fu4
  'zunhi', //准許:zun3 hi3
  'dusin', //賭神:du3 sin2
  'liyun', //利潤:li4 yun4
  'zigap', //指甲:zi3 gap5
  'fungo', //粉果:fun3 go3
  'kizit', //奇跡:ki2 zit5
  'pinon', //平安:pin2 on1
  'lapza', //蠟蔗:lap6 za4
  'siuli', //修理:siu1 li1
  'simli', //心理:sim1 li1
  'pusiu', //部首:pu4 siu3
  'dazim', //打針:da3 zim1
  'geton', //國安:get3 on1
  'dozoi', //多啜:do1 zoi4
  'zenga', //增加:zen1 ga1
  'zusuk', //煮熟:zu3 suk6
  'sanlu', //山路:san1 lu4
  'geusi', //狗屎:geu3 si3
  'yitmi', //一米:yit5 mi3
  'bauzi', //報紙:bau4 zi3
  'gauli', //高麗:gau1 li4
  'cisiu', //聚首:ci4 siu3
  'hoksu', //學士:hok6 su4
  'tigau', //提高:ti2 gau1
  'gauzi', //膠紙:gau1 zi3,餃子:gau3 zi3
  'fahok', //化學:fa4 hok6
  'capai', //車牌:ca1 pai2
  'apmau', //鴨毛:ap5 mau1
  'sinki', //升旗/新奇/星期:sin1 ki2
  'pansu', //辦事:pan4 su4
  'suzai', //薯仔:su2 zai3
  'zinng', //正午:zin4 ng3
  'mukga', //木瓜:muk5 ga1
  'hoifa', //開花:hoi1 fa1
  'lutsu', //律師:lut6 su1
  'suifa', //水花:sui3 fa1
  'momet', //磨墨:mo2 met6
  'facau', //花槽:fa1 cau2
  'manzu', //滿子:man1 zu3
  'cutai', //自大:cu4 tai4
  'aizak', //哎隻:ai2 zak5,哎隻:ai4 zak5
  'gimin', //居民:gi1 min2
  'zukza', //竹蔗:zuk5 za4
  'ngion', //軟:ngion1
  'gagak', //價格:ga4 gak5
  'yinfa', //櫻花:yin1 fa1,榮華:yin2 fa2
  'gonfo', //乾貨:gon1 fo4
  'suyap', //樹葉:su4 yap4
  'gisin', //寄信/記性:gi4 sin4
  'zoksi', //作死:zok5 si3
  'kiuti', //球體:kiu2 ti3
  'zinzu', //珍珠:zin1 zu1
  'fapun', //花盆:fa1 pun2
  'zugak', //資格:zu1 gak5
  'lokhi', //落去:lok6 hi4
  'gamsu', //減數:gam3 su4
  'gefun', //計分:ge4 fun1
  'kiung', //窮:kiung2,共:kiung4
  'bauca', //煲茶:bau1 ca2
  'zakfo', //炙火:zak5 fo3
  'sugon', //事幹:su4 gon4
  'bauza', //爆炸:bau4 za4
  'gamau', //假冒:ga3 mau4
  'futem', //湖沊:fu2 tem2
  'fogai', //火雞:fo3 gai1
  'cidit', //遲滴:ci2 dit6
  'sadam', //蛇膽:sa2 dam3
  'gimki', //禁區:gim4 ki1,禁忌:gim4 ki4
  'cinco', //清楚:cin1 co3
  'olidu', //痾痢肚:o1 li4 du3
  'vakfa', //畫畫:vak6 fa6
  'luica', //擂茶:lui2 ca2
  'dalot', //打脫:da3 lot5
  'siasu', //寫字:sia3 su4
  'saksu', //碩士:sak6 su4
  'mafan', //麻煩:ma2 fan2
  'giliu', //居留:gi1 liu2
  'disoi', //知衰:di1 soi1
  'tuzai', //兔仔:tu4 zai3
  'bosam', //波衫:bo1 sam1
  'tiyuk', //體育:ti3 yuk5
  'siubi', //手臂:siu3 bi4
  'coifa', //才華:coi2 fa2,菜花:coi4 fa1
  'simin', //市民:si4 min2
  'zitsu', //質素/質數:zit5 su4
  'kiang', //輕:kiang1
  'fosin', //火星:fo3 sin1
  'gaibi', //雞髀:gai1 bi3
  'pakzi', //白紙:pak6 zi3
  'gasan', //家山:ga1 san1
  'asiak', //阿鵲:a1 siak5
  'suciu', //絲綢:su1 ciu2
  'susit', //事實:su4 sit6,素食:su4 sit6
  'fanhe', //凡係:fan2 he4
  'batpo', //八婆:bat5 po2
  'caima', //猜碼:cai1 ma1
  'pakli', //白蟻:pak6 li1
  'pihai', //皮鞋:pi2 hai2
  'suyin', //私隱:su1 yin3,樹仁:su4 yin2
  'onsim', //安心:on1 sim1
  'gatin', //家庭:ga1 tin2
  'gotvo', //割禾:got5 vo3
  'hanhe', //還係:han2 he4
  'tiuhi', //投墟:tiu2 hi1,敨氣:tiu3 hi4
  'daizu', //帶子:dai4 zu3
  'pakfu', //白虎:pak6 fu3
  'yunhi', //運氣:yun4 hi4
  'banma', //斑馬:ban1 ma1
  'mateu', //碼頭:ma1 teu2
  'pakva', //白話:pak6 va4
  'focai', //火柴:fo3 cai2
  'konsu', //看書:kon4 su1
  'honga', //寒假:hon2 ga3
  'getzi', //國際:get5 zi4
  'laufu', //老虎:lau4 fu3
  'nglin', //魚鱗:ng2 lin1
  'ganga', //假牙:ga3 nga2
  'taibi', //大髀:tai4 bi3
  'apzai', //鴨仔:ap5 zai3
  'gaima', //雞嫲:gai1 ma2
  'kuifa', //葵花:kui2 fa1
  'subui', //字輩:su4 bui4
  'gagam', //加緊:ga1 gam3
  'gofun', //過分:go4 fun4
  'gabin', //嘉賓:ga1 bin1
  'sunng', //孫女:sun1 ng3
  'yunho', //運河:yun4 ho2
  'geuma', //狗嫲:geu3 ma2
  'siuzi', //手指:siu3 zi3
  'lizai', //驢子:li2 zai3,李仔:li3 zai3
  'lukti', //陸地:luk6 ti4
  'binsi', //摒屎:bin3 si3
  'gadai', //家底:ga1 dai3
  'poisu', //背書:poi4 su1
  'yinhi', //引起:yin3 hi3
  'suksa', //宿舍:suk5 sa4
  'mifun', //迷魂:mi2 fun2,米粉:mi3 fun3
  'misin', //迷信:mi2 sin4
  'yimca', //飲茶:yim3 ca2
  'funha', //份下:fun4 ha4
  'lausu', //老師:lau3 su1
  'zacoi', //榨菜:za coi4
  'miang', //蒙:miang1,名:miang2,命:miang4
  'sitya', //食夜:sit6 ya4
  'polan', //破爛:po4 lan4
  'tikiu', //地球:ti4 kiu2
  'giong', //疆:giong1
  'zunga', //蛀牙:zu4 nga2
  'livut', //禮物:li1 vut6
  'modau', //磨刀:mo2 dau1
  'bohai', //波鞋:bo1 hai2
  'coika', //在卡（在家）:coi1 ka1
  'zupui', //豬肺:zu1 pui4
  'gizak', //幾隻:gi3 zak5
  'vuset', //烏色:vu1 set5
  'cunca', //伸差:cun1 ca1
  'miluk', //米碌:mi3 luk5
  'tizin', //地震:ti4 zin3
  'taicu', //大暑:tai4 cu3
  'fasit', //花式:fa1 sit5
  'yimau', //羽毛:yi1 mau1
  'botzu', //發子:bot5 zu3
  'hivun', //氣溫:hi4 vun1
  'kilin', //麒麟:ki2 lin2
  'soteu', //樹頭:so1 teu2
  'hilap', //希臘:hi1 lap6
  'pofai', //破壞:po4 fai4
  'sanzu', //山豬:san1 zu1
  'honlu', //寒露:hon2 lu4
  'yiuma', //油麻:yiu2 ma2
  'mafui', //馬會:ma1 fui4
  'sunli', //順利:sun4 li4
  'gaziu', //假酒:ga3 ziu3
  'siudu', //首都:siu3 du1
  'hiyet', //喜悅:hi3 yet6
  'taufa', //桃花:tau2 fa1
  'sotva', //說話:sot5 va4
  'ngmin', //漁民:ng2 min2
  'teufu', //豆腐:teu4 fu4
  'ngiap', //𥍉:ngiap5,凹:ngiap5
  'gibun', //基本:gi1 bun2
  'getga', //國家:get5 ga1
  'lusui', //露水:lu4 sui3
  'sulim', //樹林:su4 lim2
  'sango', //山歌:san1 go1
  'zudeu', //豬兜:zu1 deu1
  'mittu', //密度:mit6 tu4
  'kisit', //其實:ki2 sit6
  'gofeu', //過埠:go4 feu4
  'hosun', //河唇:ho2 sun2
  'ziang', //精:ziang1
  'haliu', //下流:ha4 liu2
  'auziu', //澳洲:au4 ziu1
  'vuyin', //烏蠅:vu1 yin2
  'hapzu', //合資:hap6 zu1
  'sitoi', //時代:si2 toi4
  'biang', //餅:biang3,柄:biang4,屏:biang4
  'soiyi', //睡衣:soi4 yi1
  'suhok', //數學:su4 hok6
  'yintu', //印度:yin4 tu4
  'gifui', //機會:gi1 fui4
  'gaing', //雞魚:gai1 ng2
  'youyi', //由於:you2 yi1
  'dason', //打算:da3 son4
  'sipsu', //習字:sip6 su6
  'yivui', //以為:yi1 vui2
  'safui', //社會:sa1 fui4
  'soifu', //睡褲:soi4 fu4
  'gonse', //乾洗:gon1 se3
  'moihi', //煤氣:moi2 hi4
  'sigok', //死角:si3 gok5
  'suiba', //水壩:sui3 ba4
  'folun', //貨輪:fo4 lun2
  'fukvu', //服務:fuk6 vu4
  'onvub', //安穩:on1 vub3
  'yahoi', //扡痎:ya3 hoi2
  'saugi', //筲箕:sau1 gi1
  'yitse', //一世:yit5 se4
  'zokbu', //桌布:zok5 bu4
  'mhiau', //唔曉:m1 hiau3
  'zugon', //豬肝:zu1 gon1
  'ngiak', //逆:ngiak6
  'camyi', //參與:cam1 yi1
  'dauma', //刀嫲:dau1 ma2
  'manng', //滿女:man1 ng5
  'pidai', //背帶:pi4 dai4
  'yiyen', //醫院:yi1 yen4,依然:yi1 yen2
  'cinpi', //陳皮:cin2 pi2
  'coizu', //財主:coi2 zu3
  'botsa', //發蛇:bot5 sa2
  'taing', //大魚:tai4 ng2
  'kolen', //可能:ko3 len2
  'pakto', //拍拖:pak5 to1
  'soncu', //酸醋:son1 cu4
  'gacit', //價值:ga4 cit6
  'caing', //柴魚:cai2 ng2
  'caifa', //採花:cai3 fa1
  'fugui', //富貴:fu4 gui4
  'laiap', //泥鴨:lai2 ap5
  'aicin', //哎陣:ai4 cin4
  'pumun', //部門:pu4 mun2
  'aziau', //阿僬:a1 ziau2
  'calin', //車輪:ca1 lin2
  'siuak', //手戹:siu3 ak5
  'taiga', //大家:tai4 ga1
  'fahai', //花鞋:fa1 hai2
  'subau', //書包:su1 bau1
  'vuizi', //位置:vui4 zi4
  'silam', //西南:si1 lam2
  'ciang', //青:ciang1,晴:ciang2,淨:ciang4
  'sauzu', //燒豬:sau1 zu1
  'zubun', //資本:zu1 bun3
  'puizu', //肥豬:pui2 zu1
  'tusin', //土星:tu3 sin1
  'gagin', //加緊:ga1 gin3
  'kivun', //奇聞:ki2 vun2
  'dazau', //打早:da3 zau3
  'lozai', //螺仔:lo2 zai3
  'tidai', //地底:ti4 dai3
  'citsu', //植樹:cit6 su4
  'dozui', //多嘴:do1 zui3
  'cithi', //直去:cit6 hi4
  'ziyau', //紙鷂:zi3 yau4
  'sinku', //辛苦:sin1 ku3
  'cauzi', //草紙:cau3 zi3
  'lengu', //嬭菇:len4 gu1
  'yalai', //椰奶:ya2 lai1
  'ngiet', //月:ngiet6
  'caupi', //皺皮:cau2 pi2
  'zauon', //早安:zau3 on1
  'fuciu', //湖鰍:fu2 ciu1
  'pifat', //批發:pi1 fat5
  'gauzu', //餃子:gau3 zu3
  'bisoi', //比賽:bi3 soi4
  'suisa', //水蛇:sui3 sa2
  'suigo', //水果:sui3 go3
  'biali', //啤梨:bia1 li2
  'auyun', //奧運:au4 yun4
  'soima', //賽馬:soi4 ma1
  'kigai', //奇怪:ki2 gai4
  'fosit', //伙食:fo3 sit6
  'sinyi', //新衣:sin1 yi1
  'samga', //衫架:sam1 ga4
  'yitcu', //益處:yit5 cu4,一次:yit5 cu4
  'socoi', //蔬菜:so1 coi4
  'gizai', //鋸仔:gi4 zai3
  'hanzi', //限制:han4 zi4
  'zicai', //制裁:zi4 cai2
  'habai', //下擺:ha4 bai3
  'zusam', //豬糝:zu1 sam3
  'botsi', //發死:bot5 si3
  'pauca', //跑車:pau3 ca1
  'bakpo', //伯婆:bak5 po2
  'kaima', //筷孖:kai4 ma1
  'agiun', //亞軍:a1 giun1
  'dupat', //肚胈:du3 pat6
  'ciahi', //邪氣:cia2 hi4
  'vusui', //污水:vu1 sui3
  'cesim', //齊心:ce2 sim1
  'pocai', //破柴:po4 cai2
  'geson', //計算:ge4 son4
  'foyun', //貨運:fo4 yun4
  'oktuk', //惡毒:ok5 tuk5
  'camga', //參加:cam1 ga1
  'gasui', //加水:ga1 sui3
  'tiula', //頭那:tiu2 la1
  'gitdo', //幾多:git5 do1
  'gakza', //隔渣:gak5 za1
  'limau', //禮貌:li1 mau4
  'daiha', //底下:dai3 ha1
  'dagau', //打交:da3 gau1
  'lifun', //離婚:li2 fun1
  'banya', //半夜:ban4 ya4
  'mayiu', //麻油:ma2 yiu2
  'hoima', //海馬:hoi3 ma1
  'kinng', //鯨魚:kin2 ng2
  'sitca', //食茶:sit6 ca2
  'zoima', //啜碼:zoi4 ma1
  'cogam', //坐監:co1 gam1
  'fudam', //負擔:fu4 dam1
  'gigan', //機關:gi1 gan1
  'yinli', //印尼:yin4 li2
  'siuau', //手凹:siu3 au3
  'ngiam', //拈:ngiam1,黏:ngiam2
  'libai', //禮拜:li1 bai4
  'foyok', //火藥:fo3 yok6
  'tinga', //定價:tin4 ga4
  'sigai', //世界:si4 gai4
  'zufan', //煮飯:zu3 fan4
  'fudeu', //戽斗:fu4 deu3
  'oiget', //愛國:oi4 get5
  'sicon', //西餐:si1 con1
  'gindu', //京都:gin1 du1
  'ngala', //牙罅:nga2 la4
  'boksu', //博士:bok5 su4
  'sumuk', //蘇木:su1 muk5,數目:su4 muk5,樹木/數目:su4 muk5
  'pingo', //蘋果:pin2 go3
  'tailu', //大路:tai4 lu4
  'lapap', //腊鴨:lap6 ap5
  'hisin', //喜訊:hi3 sin4
  'vonha', //渾下:von2 ha4
  'tilui', //地雷:ti4 lui2
  'ngasi', //牙屎:nga2 si3
  'yitce', //一齊:yit5 ce2
  'siyok', //西藥:si1 yok6
  'sisin', //時薪:si2 sin1,時辰:si2 sin2
  'sanza', //山楂:san1 za1
  'liang', //領:liang1,靈:liang2,靚:liang4
  'tihok', //地殼:ti4 hok5
  'suisu', //瑞士:sui4 su4
  'sozai', //傻仔:so zai3
  'pudui', //部隊:pu4 dui4
  'coden', //坐等:co1 den3
  'sicut', //屎出:si3 cut5
  'makpi', //麥皮:mak6 pi2
  'yikau', //依靠:yi1 kau4
  'fanca', //反差:fan3 ca1
  'cucai', //自在:cu4 cai4
  'tonhi', //斷氣:ton1 hi4
  'sukme', //叔姆:suk5 me1
  'mitga', //蜜瓜:mit6 ga1
  'gimsu', //禁書:gim4 su1
  'pifui', //皮費:pi2 fui4
  'casau', //叉燒:ca1 sau1
  'kaiga', //㧡枷:kai1 ga1
  'cugok', //自覺:cu4 gok5
  'dazap', //打摺:da3 zap5
  'famoi', //話梅:fa4 moi2
  'taiyi', //大姨:tai4 yi2
  'lonlu', //暖壺:lon1 lu2
  'sakmo', //石磨:sak6 mo4
  'ngien', //年:ngien2,願:ngien4
  'camsu', //杉樹:cam4 su4
  'auyen', //澳元:au4 yen2
  'guigi', //規矩:gui1 gi1
  'paifo', //派貨:pai4 fo4
  'cabau', //茶煲:ca2 bau1
  'gasoi', //加稅:ga1 soi4
  'yiheu', //以後:yi1 heu4
  'dansu', //單數:dan1 su4
  'hipau', //起泡:hi3 pau1
  'logau', //螺鉸:lo2 gau4
  'getfo', //國貨:get5 fo4
  'sanvo', //山窩:san1 vo1
  'aumun', //澳門:au4 mun2
  'fazen', //畫展:fa4 zen3
  'getgo', //國歌:get5 go1
  'sufuk', //舒服:su1 fuk6
  'zayok', //炸藥:za4 yok6
  'ngteu', //魚頭:ng2 teu2
  'cabui', //茶杯:ca2 bui1
  'sukui', //書櫃:su1 kui4
  'caugu', //草菇:cau3 gu1
  'tiyit', //第一:ti4 yit5
  'pafan', //扒飯:pa1 fan4
  'capso', //插疏:cap5 so1
  'tuksa', //毒蛇:tuk6 sa2
  'yingi', //意義:yi4 ngi4
  'yigon', //衣冠/醫官:yi1 gon1,醫館:yi1 gon3
  'paksu', //柏樹:pak5 su4
  'gevak', //計劃:ge4 vak6
  'fatsa', //發射:fat5 sa4
  'metng', //墨魚:met6 ng2
  'nggut', //魚骨:ng2 gut5
  'gimzu', //金豬:gim1 zu1
  'suzen', //書展:su1 zen3
  'gasin', //加薪:ga1 sin1
  'cinga', //親家:cin1 ga1
  'fovut', //貨物:fo4 vut6
  'butgo', //不過:but5 go3
  'zisit', //知識:zi4 sit5
  'yisut', //醫術:yi1 sut5
  'siyin', //死因:si3 yin1
  'yunmu', //韻母:yun4 mu1
  'ciong', //槍:ciong1,搶:ciong3,像:ciong4
  'sifut', //屎窟:si3 fut1
  'pipin', //批評:pi1 pin2
  'lipha', //立夏:lip6 ha4
  'tuhin', //圖形:tu2 hin2
  'gasit', //加息:ga1 sit5
  'tonci', //團聚:ton2 ci4
  'githi', //激氣:git5 hi4
]
